### ISSUE TITLE
questions on full simulation truth matching

### ISSUE THREAD

**Issue by c-dilks** [c-dilks/largex-eic#81]
Hi @sanghwapark, in the code below, why is `mineta` so large? Should we also match based on distance in azimuth as well? How often does this "give it another shot" part run?
https://github.com/c-dilks/largex-eic/blob/8866470d87d35380ba56ced6cd0df0e37d2ca0c8/src/AnalysisDD4hep.cxx#L221-L248

**Comment by sanghwapark** [comment]
Hi, the initial value of the mineta is set large on purpose (as the start of a simple minimum search method). Since there is pid matching as a first screening I didn't add more matching such as azimuth, but we can certainly do that. I didn't check in detail how often this "give it another shot" is called. This is not meant to be a primary way to do mcID matching, but there are some reconstructed particles without matching mcIDs. Perhaps I should test how much this alternative search can do.
